tab1<-     tabPanel("Data input/preprocessing", 
                    sidebarLayout(
                      sidebarPanel(
                        
                        #Test dataset or file input
                        radioButtons(inputId= "testData", label = "Do you want to work with a test dataset?",
                                     choices = c("Yes"="1", "No, I want to upload a dataset"= 2), selected = character(0), inline=TRUE),

                        conditionalPanel(
                          condition= "input.testData == 1",
                          #load test data
                          helpText(strong("We'll work with test data")) 
                        ),
                        
                        conditionalPanel(
                          condition = "input.testData== 2",
                          ### Data upload ###
                          radioButtons(inputId= "typeData", label = "How is your read count data organized?",
                                       choices = c("count matrix"= "1", "10X" = 2, "Rds object" = 3), selected = character(0), inline=TRUE),
                          helpText("Data in a count matrix format: a matrix with cell-barcodes as columns and features as rows (.csv or .tsv)"),
                          helpText("Data in 10X format: output files generated by the 10X Genomics Cellranger pipeline"),
                          helpText("Rds object: An Rds data object generated from this pipeline or a count matrix transformed to an Rds object as described in the Help Page")
                        ),
                        
                        conditionalPanel(
                          condition = "input.typeData == 1 & input.testData == 2",
                          fileInput(inputId="csvFile", NULL, buttonLabel = "Upload .csv or .tsv",
                                    multiple = FALSE, accept = c(".csv", ".tsv")),
                          textOutput("uploadCsvValidation"),
                          
                          ),
                        
                        
                        conditionalPanel(
                          condition = "input.typeData == 2 & input.testData == 2",
                          #radioButtons(inputId= "type10X", label = NULL,
                          #             choices = c("Locally stored data"= 1, "Download from GEO" = 2), selected = character(0), inline=TRUE)
                          helpText("You can provide .mtx or gzipped versions (.mtx.gz)"),
                          fileInput(inputId="mtxInput", NULL, buttonLabel = "Upload count matrix",
                                    multiple = FALSE, accept = c(".mtx", ".mtx.gz")),
                          textOutput("uploadmtxValidation"),
                          #textInput(inputId="mtxInput", "Filename of matrix", value = NULL),
                          
                          helpText("You can provide .tsv or gzipped versions (.tsv.gz)"),
                          fileInput(inputId="genes10XInput", NULL, buttonLabel = "Upload genes",
                                    multiple = FALSE, accept = c(".tsv", ".tsv.gz")),
                          textOutput("uploadgenes10XValidation"),
                          #textInput(inputId="genes10XInput", "Filename of genes", value = NULL),
                          
                          helpText("You can provide .tsv or gzipped versions (.tsv.gz)"),
                          helpText("This file is optional, as we don't perform any analysis with barcodes"),
                          fileInput(inputId="barcodes10XInput", NULL, buttonLabel = "Upload barcodes",
                                    multiple = FALSE, accept = c(".tsv", ".tsv.gz")),
                          textOutput("uploadbarcodes10XValidation")
                          
                          ),
                        
                        conditionalPanel(
                          condition = "input.typeData == 3 & input.testData == 2",
                          fileInput(inputId="rdsFile", NULL, buttonLabel = "Upload .rds",
                                    multiple = FALSE, accept = ".rds"),
                          textOutput("uploadRdsValidation"),
                          
                          ),

                        
                        ###### QC analysis and  plots #####
                        
                        #read data
                        actionButton("startQC", "Read data"),
                        
                        span(textOutput("readData") %>% withSpinner(), style = "color:dodgerblue"),
                        
                        #add metadata
                        helpText("We have to add some metadata regarding the genes present in your dataset"),
                        #set gene annotation parameteres
                        radioButtons(inputId= "typeGeneId", label = "How are features (genes) annotated?",
                                     choices = c("Gene names" = TRUE, "Ensembl IDs" = FALSE ), selected = character(0), inline=TRUE),
                        helpText("Note that in the case of 10X files we follow the Ensembl annotation"),
                        #set organism parameteres
                        radioButtons(inputId= "typeOrganism", label = "Which organism comes your data from?",
                                     choices = c("Homo sapiens", "Mus musculus" ), selected = character(0), inline=TRUE),
                        
                        actionButton("addMetadata", 'Add gene annotations'),
                        
                        span(textOutput("paramsAddMetadata") %>% withSpinner(), style = "color:dodgerblue"),
                        
                        #inital minimal filtering
                        helpText("At this stage we'll filter out cells with less than 100 UMIs"),
                        actionButton("initFiltering", 'Minimal filtering'),
                        span(textOutput("initDataFilt") %>% withSpinner(), style = "color:dodgerblue"),
                        
                        #save data as rds object
                        helpText("Now we'll save data with metadata in a Rds object"),
                        #textInput(inputId="dataName", "Please provide a name for your dataset", 
                        #          value = "Enter a name..."),
                        helpText("You can download the Rds object (optional but helpful)"),
                        #actionButton("initDownload", 'Save Rds object'),
                        downloadButton("initDownload", 'Save Rds object')
                        #span(textOutput("dataNameValidation")%>% withSpinner(), style = "color:dodgerblue"),
                        
                        
                        
                      ),
                      
                      
                      mainPanel(
                        
                        
                      )
                    )
)
